/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Form;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marsa
 */
public class FormMasterBarang extends javax.swing.JPanel {

    /**
     * Creates new form FormMaster1
     */
    public FormMasterBarang() {
        initComponents();
        
        tabel.setModel(tbl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        pDataBarang = new javax.swing.JPanel();
        lbDataBarang = new javax.swing.JLabel();
        bTambah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new Swing.Table();
        pTambahBarang = new javax.swing.JPanel();
        lbTambahBarang = new javax.swing.JLabel();
        bSimpan = new javax.swing.JButton();
        bBatal = new javax.swing.JButton();
        lbKodeBarang = new javax.swing.JLabel();
        tfKodeBarang = new javax.swing.JTextField();
        lbNamaBarang = new javax.swing.JLabel();
        tfNamaBarang = new javax.swing.JTextField();
        lbJenisBarang = new javax.swing.JLabel();
        cbJenisBarang = new javax.swing.JComboBox<>();
        lbJumlahBarang = new javax.swing.JLabel();
        tfJumlahBarang = new javax.swing.JTextField();

        setOpaque(false);
        setLayout(new java.awt.CardLayout());

        mainPanel.setOpaque(false);
        mainPanel.setLayout(new java.awt.CardLayout());

        pDataBarang.setOpaque(false);

        lbDataBarang.setFont(new java.awt.Font("SansSerif", 1, 25)); // NOI18N
        lbDataBarang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbDataBarang.setText("Data Barang");
        lbDataBarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        bTambah.setBackground(new java.awt.Color(245, 245, 245));
        bTambah.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        bHapus.setBackground(new java.awt.Color(245, 245, 245));
        bHapus.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bUbah.setBackground(new java.awt.Color(245, 245, 245));
        bUbah.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        tabel.setBackground(new java.awt.Color(245, 245, 245));
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "Jenis Barang", "Jumlah Barang"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        javax.swing.GroupLayout pDataBarangLayout = new javax.swing.GroupLayout(pDataBarang);
        pDataBarang.setLayout(pDataBarangLayout);
        pDataBarangLayout.setHorizontalGroup(
            pDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataBarangLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pDataBarangLayout.createSequentialGroup()
                        .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
                    .addComponent(lbDataBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        pDataBarangLayout.setVerticalGroup(
            pDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataBarangLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbDataBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(pDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        mainPanel.add(pDataBarang, "card2");

        pTambahBarang.setOpaque(false);

        lbTambahBarang.setFont(new java.awt.Font("SansSerif", 1, 25)); // NOI18N
        lbTambahBarang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTambahBarang.setText("Tambah Data Barang");
        lbTambahBarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        bSimpan.setBackground(new java.awt.Color(245, 245, 245));
        bSimpan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bBatal.setBackground(new java.awt.Color(245, 245, 245));
        bBatal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        bBatal.setText("Batal");
        bBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatalActionPerformed(evt);
            }
        });

        lbKodeBarang.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbKodeBarang.setText("Kode Barang");

        lbNamaBarang.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbNamaBarang.setText("Nama Barang");

        lbJenisBarang.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbJenisBarang.setText("Jenis Barang");

        cbJenisBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Jenis -", "Makanan ", "Minuman" }));

        lbJumlahBarang.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbJumlahBarang.setText("Jumlah Barang");

        javax.swing.GroupLayout pTambahBarangLayout = new javax.swing.GroupLayout(pTambahBarang);
        pTambahBarang.setLayout(pTambahBarangLayout);
        pTambahBarangLayout.setHorizontalGroup(
            pTambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTambahBarangLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pTambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbJenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pTambahBarangLayout.createSequentialGroup()
                        .addComponent(bSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfKodeBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
                    .addComponent(tfNamaBarang)
                    .addComponent(tfJumlahBarang)
                    .addComponent(cbJenisBarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTambahBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        pTambahBarangLayout.setVerticalGroup(
            pTambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTambahBarangLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbTambahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(pTambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(lbKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(tfKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lbNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(tfNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lbJenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(cbJenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lbJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(tfJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        mainPanel.add(pTambahBarang, "card3");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatalActionPerformed
        mainPanel.removeAll();
        mainPanel.add(pDataBarang);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_bBatalActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(pTambahBarang);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_bTambahActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(pDataBarang);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        tabel.addRow(new Object[]{
            tfKodeBarang.getText(),
            tfNamaBarang.getText(),
            cbJenisBarang.getSelectedItem(),
            tfJumlahBarang.getText()
        });
        
        tfKodeBarang.setText("");
        tfNamaBarang.setText("");
        cbJenisBarang.setSelectedIndex(0);
        tfJumlahBarang.setText("");
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        DefaultTableModel tblModel = (DefaultTableModel) tabel.getModel();
         
        if (tabel.getSelectedRowCount() == 1 ) {
             tblModel.removeRow(tabel.getSelectedRow());
        }
    }//GEN-LAST:event_bHapusActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        DefaultTableModel tblModel = (DefaultTableModel)tabel.getModel();
        
        String tblKode = tblModel.getValueAt(tabel.getSelectedRow(), 0).toString();
        String tblNama = tblModel.getValueAt(tabel.getSelectedRow(), 1).toString();
        String tblJenis = tblModel.getValueAt(tabel.getSelectedRow(), 2).toString();
        String tblJumlah = tblModel.getValueAt(tabel.getSelectedRow(), 3).toString();
    }//GEN-LAST:event_tabelMouseClicked

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        DefaultTableModel tblModel = (DefaultTableModel)tabel.getModel();
        
        if (tabel.getSelectedRowCount() == 1) {
            int selectedRow = tabel.getSelectedRow();

            String Kode = tblModel.getValueAt(selectedRow, 0).toString();
            String Nama = tblModel.getValueAt(selectedRow, 1).toString();
            String Jenis = tblModel.getValueAt(selectedRow, 2).toString();
            String Jumlah = tblModel.getValueAt(selectedRow, 3).toString();

            tfKodeBarang.setText(Kode);
            tfNamaBarang.setText(Nama);
            cbJenisBarang.setSelectedItem(Jenis);
            tfJumlahBarang.setText(Jumlah);

            mainPanel.removeAll();
            mainPanel.add(pTambahBarang);
            mainPanel.repaint();
            mainPanel.revalidate();
            
            tblModel.removeRow(tabel.getSelectedRow());
        }
    }//GEN-LAST:event_bUbahActionPerformed

    int Baris = 0;
    static Object kolom[] = {"Kode", "Nama", "Jenis", "Jumlah"};
    DefaultTableModel tbl = new DefaultTableModel(kolom, Baris);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBatal;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bUbah;
    private javax.swing.JComboBox<String> cbJenisBarang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDataBarang;
    private javax.swing.JLabel lbJenisBarang;
    private javax.swing.JLabel lbJumlahBarang;
    private javax.swing.JLabel lbKodeBarang;
    private javax.swing.JLabel lbNamaBarang;
    private javax.swing.JLabel lbTambahBarang;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pDataBarang;
    private javax.swing.JPanel pTambahBarang;
    private Swing.Table tabel;
    private javax.swing.JTextField tfJumlahBarang;
    private javax.swing.JTextField tfKodeBarang;
    private javax.swing.JTextField tfNamaBarang;
    // End of variables declaration//GEN-END:variables
}
